name: my_profile
description: "A showcase Flutter project with integration of  stacked architecture."
publish_to: 'none'
authors:
  - Pranil Shah

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State Management
  stacked: 3.4.2
  get_it: 7.6.7


  # UI
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  page_transition: 2.1.0
  oktoast: 3.4.0
  lottie: 3.0.0
  intl: 0.18.1


  # Firebase
  firebase_core: 2.28.0


  # Utils
  image_picker: 1.0.7

  # Data
  synchronized: 3.1.0+1
  shared_preferences: 2.2.2

flutter_gen:
  output: lib/generated/
  line_length: 2000 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.1
  build_runner:
  flutter_gen_runner:
  intl_utils: 2.8.7

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/lottie/

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true